### ISSUE TITLE
project does not working with tsc -w

### ISSUE THREAD

**Issue by nigel-dewar** [iamclaytonray/tes#4]
Hi Clayton,

When I make a changes to project.json, using tsw -w instead of just tsc the api does not work.

I was wondering, how would you have this project so it automatically rebuilds on new changes?

Cheers

**Comment by iamclaytonray** [comment]
You would just `tsc -w` to watch files for changes. In another terminal tab/window, run `nodemon ./build/index.js`

**Comment by nigel-dewar** [comment]
Wow that was a FAST response! Happy new year by the way. Thank you I will do this. Its not possible to have one command from project.json that does this?

**Comment by iamclaytonray** [comment]
Yep, you can add it to the `scripts` in `package.json`.

**Comment by iamclaytonray** [comment]
Did you clone or fork this repo?

**Comment by nigel-dewar** [comment]
I cloned this one

**Comment by nigel-dewar** [comment]
here is what Im doing in project.json

"scripts": {
    "server": "tsc -w && nodemon ./build/index.js",
    "start": "node ./build/index.js"
  },

**Comment by iamclaytonray** [comment]
I updated the scripts

**Comment by iamclaytonray** [comment]
Run `yarn ts:watch` in one tab and `yarn server` in another.

**Comment by nigel-dewar** [comment]
Thanks very much Clayton!!!

**Comment by iamclaytonray** [comment]
If that solves the issue for you, I'll go ahead and close the issue. Just want to confirm first 🙂

**Comment by nigel-dewar** [comment]
This solves it, it works perfectly!!! Thanks heaps for this mate!
