### ISSUE TITLE
move to async/await pattern? & add swagger?

### ISSUE THREAD

**Issue by calvyntwh** [iamclaytonray/tes#5]
would you like to move to an async/await pattern?

and use https://swagger.io to document the api?

**Comment by iamclaytonray** [comment]
Sure thing. Do you want to give it a shot? I'm more than happy to code review 🙂

**Comment by calvyntwh** [comment]
i realized that is no point doing async/ await for the routers as it will return a promise. haha this api is simple, adding it will just add more code that does the same. thanks for the offer

**Comment by calvyntwh** [comment]
maybe i'll just work on request validation.
