### ISSUE TITLE
error when running yarn server

### ISSUE THREAD

**Issue by calvyntwh** [iamclaytonray/tes#6]
`yarn run v1.3.2
$ nodemon ./build/index.js
[nodemon] 1.14.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./build/index.js index.js`
module.js:538
    throw err;
    ^

Error: Cannot find module '/home/dev/dev/tes/index.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by iamclaytonray** [comment]
Did you run `tsc` to transpile it first?

**Comment by calvyntwh** [comment]
i did not run tsc yet, should the yarn server command do that then nodemon?

**Comment by iamclaytonray** [comment]
I have a watch script (`ts:watch`) but I'll add that to the `server` script as well

**Comment by calvyntwh** [comment]
running tsc:watch

```shell
dev@dev-desktop:~/dev/tes$ yarn ts:watch
yarn run v1.3.2
$ tsc -w
src/router/PostRouter.ts(107,16): error TS2503: Cannot find namespace 'postRoutes'.
src/router/UserRouter.ts(102,16): error TS2503: Cannot find namespace 'userRoutes'.
10:03:36 - Compilation complete. Watching for file changes.
```

**Comment by calvyntwh** [comment]
maybe i'll test with a fresh clone

**Comment by iamclaytonray** [comment]
Sure, go for it. I just ran the script and it worked for me. Let me know how it works out

**Comment by calvyntwh** [comment]
fresh clone works thanks

**Comment by calvyntwh** [comment]
prolly something wrong with my fork

**Comment by iamclaytonray** [comment]
Maybe. I haven't really maintained this either.
